"use strict";
// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file SampleMessage.proto (package huddle01.observer.schema, syntax proto2)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.SampleMessage = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from message huddle01.observer.schema.SampleMessage
 */
class SampleMessage extends protobuf_1.Message {
    /**
     * @generated from field: required string serviceId = 1;
     */
    serviceId;
    /**
     * @generated from field: required string mediaUnitId = 2;
     */
    mediaUnitId;
    /**
     * @generated from field: required string roomId = 3;
     */
    roomId;
    /**
     * @generated from field: required string callId = 4;
     */
    callId;
    /**
     * @generated from field: required string clientId = 5;
     */
    clientId;
    /**
     * @generated from field: required string sampleInBase64 = 6;
     */
    sampleInBase64;
    /**
     * @generated from field: optional string peerId = 7;
     */
    peerId;
    /**
     * used when we replay the samples from a previously saved file
     * in this case we should not save the samples again
     *
     * @generated from field: optional bool replay = 8;
     */
    replay;
    /**
     * @generated from field: optional string userId = 9;
     */
    userId;
    /**
     * used to add some metadata by the connection received the sample first
     *
     * @generated from field: optional string connectionMetadata = 10;
     */
    connectionMetadata;
    constructor(data) {
        super();
        protobuf_1.proto2.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto2;
    static typeName = "huddle01.observer.schema.SampleMessage";
    static fields = protobuf_1.proto2.util.newFieldList(() => [
        { no: 1, name: "serviceId", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
        { no: 2, name: "mediaUnitId", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
        { no: 3, name: "roomId", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
        { no: 4, name: "callId", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
        { no: 5, name: "clientId", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
        { no: 6, name: "sampleInBase64", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
        { no: 7, name: "peerId", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 8, name: "replay", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
        { no: 9, name: "userId", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 10, name: "connectionMetadata", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    ]);
    static fromBinary(bytes, options) {
        return new SampleMessage().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SampleMessage().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SampleMessage().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto2.util.equals(SampleMessage, a, b);
    }
}
exports.SampleMessage = SampleMessage;
